export const FONTS = {
  RobotoThinItalic: 'Roboto-ThinItalic',
  RobotoThin: 'Roboto-Thin',
  RobotoSemiBoldItalic: 'Roboto-SemiBoldItalic',
  RobotoSemiBold: 'Roboto-SemiBold',
  RobotoRegular: 'Roboto-Regular',
  RobotoMediumItalic: 'Roboto-MediumItalic',
  RobotoMedium: 'Roboto-Medium',
  RobotoLightItalic: 'Roboto-LightItalic',
  RobotoLight: 'Roboto-Light',
  RobotoExtraLightItalic: 'Roboto-ExtraLightItalic',
  RobotoExtraLight: 'Roboto-ExtraLight',
  RobotoExtraBoldItalic: 'Roboto-ExtraBoldItalic',
  RobotoExtraBold: 'Roboto-ExtraBold',
  RobotoBoldItalic: 'Roboto-BoldItalic',
  RobotoBold: 'Roboto-Bold',
};
export const COLORS = {
  primary: '#E94057',
  primaryShadow: '#FFC1CC',
  chatthem: '#f56c7c',
  chatme: '#FF69B4',
  black: '#000',
  white: '#fff',
  grey: '#7a7777ff',
  bgcolor: '#F9F9F9',
  selecttxtcolor: '#F9F9F9',
  bordercolor: '#ddd',
  // New Futuristic Palette
  deepBlue: '#1a1b2e',
  purpleAccent: '#5d5fef',
  glassWhite: 'rgba(255, 255, 255, 0.95)',
  softShadow: '#E9405733',
  gold: '#FFD700',
  inputBg: '#f9fafb',
  textPrimary: '#1A1A1A',
  textSecondary: '#666',
  textPlaceholder: '#999',
  successGreen: '#4ade80',
  primaryDark: '#8A0E2A',
};
