export const FONTS = {
  RobotoThinItalic: 'Roboto-ThinItalic',
  RobotoThin: 'Roboto-Thin',
  RobotoSemiBoldItalic: 'Roboto-SemiBoldItalic',
  RobotoSemiBold: 'Roboto-SemiBold',
  RobotoRegular: 'Roboto-Regular',
  RobotoMediumItalic: 'Roboto-MediumItalic',
  RobotoMedium: 'Roboto-Medium',
  RobotoLightItalic: 'Roboto-LightItalic',
  RobotoLight: 'Roboto-Light',
  RobotoExtraLightItalic: 'Roboto-ExtraLightItalic',
  RobotoExtraLight: 'Roboto-ExtraLight',
  RobotoExtraBoldItalic: 'Roboto-ExtraBoldItalic',
  RobotoExtraBold: 'Roboto-ExtraBold',
  RobotoBoldItalic: 'Roboto-BoldItalic',
  RobotoBold: 'Roboto-Bold',
};
export const COLORS = {
  primary: '#E94057',
  primaryShadow: '#f56c7c',
  black: '#000',
  grey: '#7a7777ff',
  RobotoThin: 'Roboto-Thin',
  RobotoSemiBoldItalic: 'Roboto-SemiBoldItalic',
  RobotoSemiBold: 'Roboto-SemiBold',
  RobotoRegular: 'Roboto-Regular',
  RobotoMediumItalic: 'Roboto-MediumItalic',
  RobotoMedium: 'Roboto-Medium',
  RobotoLightItalic: 'Roboto-LightItalic',
  RobotoLight: 'Roboto-Light',
  RobotoExtraLightItalic: 'Roboto-ExtraLightItalic',
  RobotoExtraLight: 'Roboto-ExtraLight',
  RobotoExtraBoldItalic: 'Roboto-ExtraBoldItalic',
  RobotoExtraBold: 'Roboto-ExtraBold',
  RobotoBoldItalic: 'Roboto-BoldItalic',
  RobotoBold: 'Roboto-Bold',
};
