export const SELECTION_DATA = {
    // BASIC
    gender: ["Male", "Female", "Nonbinary"],

    selectprofilefor: ['Myself', 'My Friend', 'My Relative'],

    STATES: [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
    ],
    
    CITIES: {
  'West Bengal': ['Kolkata', 'Darjeeling', 'Siliguri', 'Asansol', 'Durgapur'],
  Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Aurangabad', 'Nashik'],
  Karnataka: ['Bangalore', 'Mysore', 'Mangalore', 'Belgaum', 'Hubli'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Trichy', 'Salem'],
  Gujarat: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Jamnagar'],
},

SUBCOMMUNITIES: [
  'Bengali',
  'Marathi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Gujarati',
  'Punjabi',
  'Odia',
],

    postedBy: ["Self", "Sibling", "Friend", "Parent", "Other"],
    age: [
        "Open for all",
        "18 - 21",
        "22 - 25",
        "26 - 30",
        "31 - 35",
        "36 - 40",
        "41+",
    ],
    height: [
        "Open for all",
        "Below 5 ft",
        "5 ft - 5 ft 3 in",
        "5 ft 4 in - 5 ft 7 in",
        "5 ft 8 in - 5 ft 11 in",
        "6 ft and above",
    ],
    maritalStatus: [
        "Open for all",
        "Single",
        "Married",
        "Divorced",
        "Widowed",
    ],
    haveChildren: ["Open for all", "No", "Ok, if not staying together"],
    anyDisability: ["No", "Partial", "Complete", "Open for all"],

    // RELIGIOUS
    religion: [
        "Open for all",
        "Hindu",
        "Muslim",
        "Christian",
        "Sikh",
        "Jain",
        "Buddhist",
    ],
    motherTongue: [
        "Open for all",
        "Hindi",
        "Bengali",
        "English",
        "Gujarati",
        "Tamil",
    ],
    community: ["Open for all", "General", "OBC", "SC", "ST", "Other"],
    casteNoBar: ["Yes", "No", "Open for all"],

    // FAMILY
    motherDetails: [
        "Homemaker",
        "Service - Government",
        "Service - Private",
        "Business",
        "Retired",
        "Passed Away",
        "Other",
    ],
    fatherDetails: [
        "Service - Government",
        "Service - Private",
        "Business",
        "Retired",
        "Passed Away",
        "Other",
    ],
    sisters: ["0", "1", "2", "3", "4+", "Open for all"],
    brothers: ["0", "1", "2", "3", "4+", "Open for all"],
    financialStatus: [
        "Lower",
        "Middle",
        "Upper Middle",
        "Well-Off",
        "Affluent",
        "Open for all",
    ],

    // LOCATION / EDUCATION / CAREER
    country: [
        "Open for all",
        "India",
        "USA",
        "UK",
        "Canada",
        "Australia",
        "UAE",
        "Other",
    ],
    state: [
        "Open for all",
        "West Bengal",
        "Maharashtra",
        "Delhi / NCR",
        "Karnataka",
        "Tamil Nadu",
        "Uttar Pradesh",
        "Gujarat",
        "Rajasthan",
        "Punjab",
        "Other",
    ],
    residencyStatus: [
        "Open for all",
        "Citizen",
        "Permanent Resident",
        "Work Permit",
        "Student Visa",
        "Temporary Visa",
    ],
    grewUpIn: ["India", "Abroad", "Open for all"],

    highestQualification: [
        "Less than Graduate",
        "Graduate",
        "Post Graduate",
        "Doctorate",
        "Professional Degree",
        "Diploma",
        "Open for all",
    ],
    qualification: [
        // used in partnerEducationCareer
        "Less than Graduate",
        "Graduate",
        "Post Graduate",
        "Doctorate",
        "Professional Degree",
        "Diploma",
        "Open for all",
    ],
    educationArea: [
        "Open for all",
        "Arts / Humanities",
        "Commerce / Finance",
        "Science",
        "Engineering / Technology",
        "Medicine / Health",
        "Management",
        "Legal / Law",
        "Education / Teaching",
        "Others",
    ],

    workingWith: [
        "Government",
        "Private",
        "Business",
        "Self-employed",
        "Not Working",
        "Other",
        "Open for all",
    ],
    professionArea: [
        "IT",
        "Finance",
        "Medical",
        "Education",
        "Business",
        "Engineering",
        "Other",
        "Open for all",
    ],
    workingAs: [
        "Software Professional",
        "Engineer",
        "Doctor",
        "Teacher",
        "Business Owner",
        "CA / Finance Professional",
        "Not Working",
        "Other",
        "Open for all",
    ],
    annualIncome: [
        "Open for all",
        "Up to ₹2,50,000",
        "₹2,50,001 – ₹5,00,000",
        "₹5,00,001 – ₹7,50,000",
        "₹7,50,001 – ₹10,00,000",
        "₹10,00,001 – ₹15,00,000",
        "₹15,00,001 – ₹20,00,000",
        "₹20,00,001 – ₹30,00,000",
        "₹30,00,001 – ₹50,00,000",
        "₹50,00,001 and above",
    ],

    // PARTNER
    religionCommunity: [
        "Open for all",
        "Hindu - General",
        "Hindu - Brahmin",
        "Hindu - Kshatriya",
        "Muslim - Sunni",
        "Muslim - Shia",
        "Christian - Catholic",
        "Christian - Protestant",
        "Other",
    ],
    profileManagedBy: ["Self", "Parents", "Sibling", "Relative", "Friend", "Other"],

    // LIFESTYLE
    diet: [
        "Open for all",
        "Veg",
        "Non-veg",
        "Egg",
        "Vegan",
        "Occasionally Non-veg",
    ],

    // ASTRO
    manglik: ["Yes", "No", "Doesn't Matter", "Open for all"],
    hasHoroscope: ["Open for all", "Yes", "No", "Not Applicable"],

    // OTHER
    photoSettings: [
        "Open for all",
        "Visible to all",
        "Visible to members I invite/accept",
        "Protected",
    ],
};
