
export const getNewMatchesData = () => [
  {
    id: "NM1",
    name: "Neha",
    age: 24,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photoMain2.jpeg"),
      require("../../../../assets/images/photomain4.jpeg"),
    ],
    photosCount: 3,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'2"`,
    religion: "Hindu",
    work: "IT Professional",
    location: "Chennai",
    online: true,
    lookingFor: "Him",
    astro: "Virgo",
    astroDetails: {
      manglik: "No",
      timeOfBirth: "06:30 PM",
      cityOfBirth: "Chennai",
      nakshatra: "Hasta"
    },

    // NEW FIELDS
    about:
      "Neha is a passionate IT professional who loves building delightful mobile experiences. She enjoys weekend hikes, exploring new cuisines and mentoring students in coding bootcamps. Looking for someone kind, ambitious and family-oriented.",
    hobbies: [
      { id: "h1", label: "Cooking", iconKey: "cooking" },
      { id: "h2", label: "Traveling", iconKey: "travel" },
      { id: "h3", label: "Reading", iconKey: "reading" },
    ],
    basicDetails: {
      userId: "NM1",
      age: 24,
      height: `5'2"`,
      dob: "1999-08-15",
      maritalStatus: "Never Married",
      livesIn: "Chennai, Tamil Nadu",
      hometown: "Coimbatore",
      religion: "Hindu",
      community: "Brahmin",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000001",
      email: "neha@example.com",
    },
    familyDetails: {
      fatherOccupation: "Businessman",
      motherOccupation: "Housewife",
      familyLocation: "Coimbatore",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Software Engineer",
      company: "TechWave Solutions",
      annualIncome: "8 LPA",
      college: "PSG College of Technology",
      degree: "B.Tech - Computer Science",
    },
  },

  {
    id: "NM2",
    name: "Rajni",
    age: 29,
    images: [
      require("../../../../assets/images/photomain4.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'8"`,
    religion: "Jain",
    work: "Business Analyst",
    location: "Hyderabad",
    online: false,
    lookingFor: "You",
    astro: "Cancer",
    astroDetails: {
      manglik: "Yes",
      timeOfBirth: "02:15 AM",
      cityOfBirth: "Jaipur",
      nakshatra: "Pushya"
    },

    about:
      "Rajni enjoys strategy games, long walks and experimenting with fusion recipes. She's detail-oriented in work and values open communication in relationships.",
    hobbies: [
      { id: "h1", label: "Cooking", iconKey: "cooking" },
      { id: "h2", label: "Photography", iconKey: "photography" },
      { id: "h3", label: "Fitness", iconKey: "fitness" },
    ],
    basicDetails: {
      userId: "NM2",
      age: 29,
      height: `5'8"`,
      dob: "1995-04-02",
      maritalStatus: "Never Married",
      livesIn: "Hyderabad, Telangana",
      hometown: "Jaipur",
      religion: "Jain",
      community: "Shrimali",
      diet: "Vegetarian",
    },
    contactDetails: {
      phone: "+91-9000000002",
      email: "rajni@example.com",
    },
    familyDetails: {
      fatherOccupation: "Manager",
      motherOccupation: "Teacher",
      familyLocation: "Jaipur",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Business Analyst",
      company: "InsightCorp",
      annualIncome: "12 LPA",
      college: "St. Xavier's College",
      degree: "MBA",
    },
  },

  {
    id: "NM3",
    name: "Simran",
    age: 27,
    images: [
      require("../../../../assets/images/photoMain2.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'5"`,
    religion: "Sikh",
    work: "Teacher",
    location: "Amritsar",
    online: true,
    lookingFor: "Him",
    astro: "Leo",

    about:
      "Simran is a warm-hearted school teacher who loves storytelling and theatre. She is family-centric and loves cultural festivals.",
    hobbies: [
      { id: "h1", label: "Theatre", iconKey: "theatre" },
      { id: "h2", label: "Reading", iconKey: "reading" },
      { id: "h3", label: "Gardening", iconKey: "gardening" },
    ],
    basicDetails: {
      userId: "NM3",
      age: 27,
      height: `5'5"`,
      dob: "1997-02-18",
      maritalStatus: "Never Married",
      livesIn: "Amritsar, Punjab",
      hometown: "Amritsar",
      religion: "Sikh",
      community: "Khatri",
      diet: "Vegetarian",
    },
    contactDetails: {
      phone: "+91-9000000003",
      email: "simran@example.com",
    },
    familyDetails: {
      fatherOccupation: "Retired Army",
      motherOccupation: "Housewife",
      familyLocation: "Amritsar",
      familyStatus: "Middle",
    },
    careerEducation: {
      profession: "School Teacher",
      company: "City Primary School",
      annualIncome: "4 LPA",
      college: "Punjab University",
      degree: "B.Ed",
    },
  },

  {
    id: "NM4",
    name: "Ananya",
    age: 26,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photoMain2.jpeg"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'6"`,
    religion: "Hindu",
    work: "UX Designer",
    location: "Bengaluru",
    online: true,
    lookingFor: "Him",
    astro: "Libra",

    about:
      "Ananya is a UX designer who loves minimal design and coffee. She spends free time learning illustrations and going to art galleries.",
    hobbies: [
      { id: "h1", label: "Sketching", iconKey: "sketch" },
      { id: "h2", label: "Coffee Roasting", iconKey: "coffee" },
      { id: "h3", label: "Cycling", iconKey: "cycling" },
    ],
    basicDetails: {
      userId: "NM4",
      age: 26,
      height: `5'6"`,
      dob: "1998-11-21",
      maritalStatus: "Never Married",
      livesIn: "Bengaluru, Karnataka",
      hometown: "Mysore",
      religion: "Hindu",
      community: "Iyer",
      diet: "Eggetarian",
    },
    contactDetails: {
      phone: "+91-9000000004",
      email: "ananya@example.com",
    },
    familyDetails: {
      fatherOccupation: "Government Officer",
      motherOccupation: "Teacher",
      familyLocation: "Mysore",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "UX Designer",
      company: "PixelFlow",
      annualIncome: "9 LPA",
      college: "NIE Mysore",
      degree: "B.Des",
    },
  },
  {
    id: "NM5",
    name: "Kavya",
    age: 25,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'5"`,
    religion: "Hindu",
    work: "Marketing",
    location: "Mumbai",
    online: true,
    lookingFor: "Him",
    astro: "Gemini",

    about:
      "Kavya is a marketing professional who loves social media trends and traveling. She is looking for a partner who is ambitious and fun-loving.",
    hobbies: [
      { id: "h1", label: "Traveling", iconKey: "travel" },
      { id: "h2", label: "Blogging", iconKey: "blogging" },
    ],
    basicDetails: {
      userId: "NM5",
      age: 25,
      height: `5'5"`,
      dob: "1999-05-15",
      maritalStatus: "Never Married",
      livesIn: "Mumbai, Maharashtra",
      hometown: "Pune",
      religion: "Hindu",
      community: "Maratha",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000005",
      email: "kavya@example.com",
    },
    familyDetails: {
      fatherOccupation: "Businessman",
      motherOccupation: "Housewife",
      familyLocation: "Pune",
      familyStatus: "High",
    },
    careerEducation: {
      profession: "Marketing Executive",
      company: "BrandBuzz",
      annualIncome: "10 LPA",
      college: "Mumbai University",
      degree: "MBA",
    },
  },

  {
    id: "NM6",
    name: "Meera",
    age: 28,
    images: [
      require("../../../../assets/images/photoMain2.jpeg"),
      require("../../../../assets/images/photomain4.jpeg"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'7"`,
    religion: "Sikh",
    work: "Architect",
    location: "Delhi",
    online: false,
    lookingFor: "Him",
    astro: "Libra",

    about:
      "Meera is an architect who loves designing sustainable homes. She enjoys painting and visiting art galleries in her free time.",
    hobbies: [
      { id: "h1", label: "Painting", iconKey: "painting" },
      { id: "h2", label: "Design", iconKey: "design" },
    ],
    basicDetails: {
      userId: "NM6",
      age: 28,
      height: `5'7"`,
      dob: "1996-08-20",
      maritalStatus: "Never Married",
      livesIn: "Delhi, NCR",
      hometown: "Chandigarh",
      religion: "Sikh",
      community: "Jat",
      diet: "Vegetarian",
    },
    contactDetails: {
      phone: "+91-9000000006",
      email: "meera@example.com",
    },
    familyDetails: {
      fatherOccupation: "Architect",
      motherOccupation: "Teacher",
      familyLocation: "Chandigarh",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Architect",
      company: "GreenSpaces",
      annualIncome: "15 LPA",
      college: "CCA Chandigarh",
      degree: "B.Arch",
    },
  },
];

// 📌 RECENT VISITORS DATA (3 profiles)
export const getRecentVisitorsData = () => [
  {
    id: "RV1",
    name: "Ayesha",
    age: 26,
    images: [
      require("../../../../assets/images/photomain.png"),
      require("../../../../assets/images/photoMain2.jpeg"),
    ],
    photosCount: 2,
    height: `5'4"`,
    religion: "Muslim",
    work: "Software Developer",
    location: "Lucknow",
    online: true,
    lookingFor: "Him",
    astro: "Pisces",

    about:
      "Ayesha is a full-stack developer who enjoys UX, performance tuning and mentoring juniors. She loves street food and weekend runs.",
    hobbies: [
      { id: "h1", label: "Running", iconKey: "running" },
      { id: "h2", label: "Cooking", iconKey: "cooking" },
    ],
    basicDetails: {
      userId: "RV1",
      age: 26,
      height: `5'4"`,
      dob: "1998-01-10",
      maritalStatus: "Never Married",
      livesIn: "Lucknow, Uttar Pradesh",
      hometown: "Lucknow",
      religion: "Muslim",
      community: "Sunni",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000101",
      email: "ayesha@example.com",
    },
    familyDetails: {
      fatherOccupation: "Engineer",
      motherOccupation: "Housewife",
      familyLocation: "Lucknow",
      familyStatus: "Middle",
    },
    careerEducation: {
      profession: "Software Developer",
      company: "ByteCraft",
      annualIncome: "7 LPA",
      college: "Institute of Engineering Lucknow",
      degree: "B.Tech - IT",
    },
  },

  {
    id: "RV2",
    name: "Karina",
    age: 30,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain4.jpeg"),
    ],
    photosCount: 2,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'9"`,
    religion: "Hindu",
    work: "Architect",
    location: "Jaipur",
    online: false,
    lookingFor: "Her",
    astro: "Scorpio",

    about:
      "Karina is an architect who blends modern aesthetics with sustainable practices. She likes pottery and loves cultural heritage walks.",
    hobbies: [
      { id: "h1", label: "Pottery", iconKey: "pottery" },
      { id: "h2", label: "Travel", iconKey: "travel" },
    ],
    basicDetails: {
      userId: "RV2",
      age: 30,
      height: `5'9"`,
      dob: "1994-06-07",
      maritalStatus: "Never Married",
      livesIn: "Jaipur, Rajasthan",
      hometown: "Jaipur",
      religion: "Hindu",
      community: "Rajasthan",
      diet: "Vegetarian",
    },
    contactDetails: {
      phone: "+91-9000000102",
      email: "karina@example.com",
    },
    familyDetails: {
      fatherOccupation: "Business",
      motherOccupation: "Teacher",
      familyLocation: "Jaipur",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Architect",
      company: "ArchiForm",
      annualIncome: "14 LPA",
      college: "SPA Bhopal",
      degree: "B.Arch",
    },
  },

  {
    id: "RV3",
    name: "Natasha",
    age: 29,
    images: [
      require("../../../../assets/images/photoMain2.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    height: `5'6"`,
    religion: "Christian",
    work: "Professor",
    location: "Bhopal",
    online: true,
    lookingFor: "Him",
    astro: "Aries",

    about:
      "Natasha teaches literature and mentors the debate team. She loves classical music and is an avid reader of world fiction.",
    hobbies: [
      { id: "h1", label: "Reading", iconKey: "reading" },
      { id: "h2", label: "Music", iconKey: "music" },
    ],
    basicDetails: {
      userId: "RV3",
      age: 29,
      height: `5'6"`,
      dob: "1995-09-12",
      maritalStatus: "Never Married",
      livesIn: "Bhopal, Madhya Pradesh",
      hometown: "Bhopal",
      religion: "Christian",
      community: "Syrian Christian",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000103",
      email: "natasha@example.com",
    },
    familyDetails: {
      fatherOccupation: "Professor",
      motherOccupation: "Accountant",
      familyLocation: "Bhopal",
      familyStatus: "Middle",
    },
    careerEducation: {
      profession: "Professor",
      company: "City University",
      annualIncome: "6 LPA",
      college: "City University",
      degree: "M.A - English",
    },
  },

  {
    id: "RV4",
    name: "Sanya",
    age: 24,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'3"`,
    religion: "Christian",
    work: "Designer",
    location: "Pune",
    online: true,
    lookingFor: "Him",
    astro: "Cancer",

    about:
      "Sanya is a graphic designer who loves creating brand identities. She enjoys photography and weekend getaways.",
    hobbies: [
      { id: "h1", label: "Photography", iconKey: "photography" },
      { id: "h2", label: "Travel", iconKey: "travel" },
    ],
    basicDetails: {
      userId: "RV4",
      age: 24,
      height: `5'3"`,
      dob: "2000-02-14",
      maritalStatus: "Never Married",
      livesIn: "Pune, Maharashtra",
      hometown: "Goa",
      religion: "Christian",
      community: "Goan Catholic",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000104",
      email: "sanya@example.com",
    },
    familyDetails: {
      fatherOccupation: "Musician",
      motherOccupation: "Teacher",
      familyLocation: "Goa",
      familyStatus: "Middle",
    },
    careerEducation: {
      profession: "Graphic Designer",
      company: "CreativeStudio",
      annualIncome: "6 LPA",
      college: "Goa College of Art",
      degree: "BFA",
    },
  },
];

// 📌 PREMIUM MATCHES DATA (5 profiles)
export const getPremiumMatchesData = () => [
  {
    id: "P1",
    name: "Amrita",
    age: 28,
    images: [
      require("../../../../assets/images/photoMain2.jpeg"),
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain4.jpeg"),
    ],
    photosCount: 3,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'10"`,
    religion: "Hindu",
    work: "Engineer",
    location: "Mumbai",
    online: true,
    lookingFor: "You",
    astro: "Aries",

    about:
      "Amrita is a systems engineer with a love for building IoT solutions. She enjoys classical dance and weekend trekking.",
    hobbies: [
      { id: "h1", label: "Dance", iconKey: "dance" },
      { id: "h2", label: "Trekking", iconKey: "trek" },
      { id: "h3", label: "Cooking", iconKey: "cooking" },
    ],
    basicDetails: {
      userId: "P1",
      age: 28,
      height: `5'10"`,
      dob: "1996-03-05",
      maritalStatus: "Never Married",
      livesIn: "Mumbai, Maharashtra",
      hometown: "Surat",
      religion: "Hindu",
      community: "Patel",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000201",
      email: "amrita@example.com",
    },
    familyDetails: {
      fatherOccupation: "Businessman",
      motherOccupation: "Housewife",
      familyLocation: "Surat",
      familyStatus: "High",
    },
    careerEducation: {
      profession: "Systems Engineer",
      company: "InnoTech",
      annualIncome: "22 LPA",
      college: "IIT Bombay",
      degree: "B.Tech",
    },
  },

  {
    id: "P2",
    name: "Priya",
    age: 25,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain.png"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'3"`,
    religion: "Muslim",
    work: "Designer",
    location: "Delhi",
    online: false,
    lookingFor: "Her",
    astro: "Taurus",

    about:
      "Priya is a UX/UI designer focusing on accessible digital products. She loves sketching and indie music.",
    hobbies: [
      { id: "h1", label: "Sketching", iconKey: "sketch" },
      { id: "h2", label: "Music", iconKey: "music" },
    ],
    basicDetails: {
      userId: "P2",
      age: 25,
      height: `5'3"`,
      dob: "1999-12-11",
      maritalStatus: "Never Married",
      livesIn: "Delhi, NCR",
      hometown: "Noida",
      religion: "Muslim",
      community: "Sunni",
      diet: "Eggetarian",
    },
    contactDetails: {
      phone: "+91-9000000202",
      email: "priya@example.com",
    },
    familyDetails: {
      fatherOccupation: "Officer",
      motherOccupation: "Teacher",
      familyLocation: "Noida",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Designer",
      company: "DesignHub",
      annualIncome: "8 LPA",
      college: "NIFT",
      degree: "B.Des",
    },
  },

  {
    id: "P3",
    name: "Roshni",
    age: 30,
    images: [require("../../../../assets/images/photomain4.jpeg")],
    photosCount: 1,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'9"`,
    religion: "Sikh",
    work: "Manager",
    location: "Bangalore",
    online: true,
    lookingFor: "You",
    astro: "Gemini",

    about:
      "Roshni is a product manager who enjoys mentoring startups. She values honesty and a good sense of humour.",
    hobbies: [
      { id: "h1", label: "Startup Mentoring", iconKey: "mentoring" },
      { id: "h2", label: "Reading", iconKey: "reading" },
    ],
    basicDetails: {
      userId: "P3",
      age: 30,
      height: `5'9"`,
      dob: "1994-07-20",
      maritalStatus: "Never Married",
      livesIn: "Bangalore, Karnataka",
      hometown: "Lucknow",
      religion: "Sikh",
      community: "Khatri",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000203",
      email: "roshni@example.com",
    },
    familyDetails: {
      fatherOccupation: "Doctor",
      motherOccupation: "Professor",
      familyLocation: "Lucknow",
      familyStatus: "High",
    },
    careerEducation: {
      profession: "Product Manager",
      company: "CloudNest",
      annualIncome: "30 LPA",
      college: "BITS Pilani",
      degree: "M.E / MBA",
    },
  },

  {
    id: "P4",
    name: "Ankita",
    age: 27,
    images: [
      require("../../../../assets/images/photomain.png"),
      require("../../../../assets/images/photoMain2.jpeg"),
    ],
    photosCount: 2,
    isVip: false,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'4"`,
    religion: "Christian",
    work: "Doctor",
    location: "Pune",
    online: false,
    lookingFor: "Her",
    astro: "Leo",

    about:
      "Ankita is a pediatrician who loves helping children. In free time she volunteers at animal shelters and enjoys pottery.",
    hobbies: [
      { id: "h1", label: "Volunteering", iconKey: "volunteer" },
      { id: "h2", label: "Pottery", iconKey: "pottery" },
    ],
    basicDetails: {
      userId: "P4",
      age: 27,
      height: `5'4"`,
      dob: "1996-05-06",
      maritalStatus: "Never Married",
      livesIn: "Pune, Maharashtra",
      hometown: "Pune",
      religion: "Christian",
      community: "Syrian Christian",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000204",
      email: "ankita@example.com",
    },
    familyDetails: {
      fatherOccupation: "Business",
      motherOccupation: "Housewife",
      familyLocation: "Pune",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Doctor",
      company: "Sunrise Hospital",
      annualIncome: "18 LPA",
      college: "BJ Medical College",
      degree: "MBBS",
    },
  },

  {
    id: "P5",
    name: "Riya",
    age: 26,
    images: [
      require("../../../../assets/images/photomain3.jpeg"),
      require("../../../../assets/images/photomain4.jpeg"),
    ],
    photosCount: 2,
    isVip: true,
    vipBadge: require("../../../../assets/images/vip_badge.png"),
    normalBadge: require("../../../../assets/images/crown.png"),
    height: `5'5"`,
    religion: "Hindu",
    work: "Marketing Manager",
    location: "Pune",
    online: true,
    lookingFor: "Him",
    astro: "Scorpio",

    about:
      "Riya heads product marketing and is passionate about storytelling and brand strategy. She loves hiking and experimental cooking.",
    hobbies: [
      { id: "h1", label: "Hiking", iconKey: "hiking" },
      { id: "h2", label: "Cooking", iconKey: "cooking" },
    ],
    basicDetails: {
      userId: "P5",
      age: 26,
      height: `5'5"`,
      dob: "1998-10-17",
      maritalStatus: "Never Married",
      livesIn: "Pune, Maharashtra",
      hometown: "Pune",
      religion: "Hindu",
      community: "Maratha",
      diet: "Non-Veg",
    },
    contactDetails: {
      phone: "+91-9000000205",
      email: "riya@example.com",
    },
    familyDetails: {
      fatherOccupation: "Retired",
      motherOccupation: "Teacher",
      familyLocation: "Pune",
      familyStatus: "Upper Middle",
    },
    careerEducation: {
      profession: "Marketing Manager",
      company: "MarketMinds",
      annualIncome: "12 LPA",
      college: "Symbiosis",
      degree: "MBA",
    },
  },
];
