export const COMMUNITIES = [
    "Open for all",
    "Brahmin",
    "Reddy",
    "Kamma",
    "Kapu",
    "Vokkaliga / Gowda",
    "Lingayat",
    "Nair",
    "Kongu Vellala Gounder",
    "Chettiar",
    "Mudaliyar / Pillai",
    "Naidu",
    "Balija",
    "Vanniyar / Palli",
    "Thevar / Mukkulathor",
    "Nadar",
    "Vellalar",
    "Arya Vysya",
    "Devanga",
    "Rajput",
    "Agarwal / Bania",
    "Maratha",
    "Jat",
    "Patidar / Patel",
    "Yadav / Ahir",
    "Kayastha",
    "Arora / Khatri",
    "Viswakarma / Vishwakarma",
    "Ezhava / Thiyya",
    "Billava",
    "Bunt / Shetty",
    "Scheduled Caste (SC)",
    "Scheduled Tribe (ST)",
    "Kshatriya",
    "Vaishya",
    "Bhumihar",
    "Tyagi",
    "Saini",
    "Kuruba",
    "Vysya",
    "Others"
];

export const SUB_COMMUNITIES = {
    "Brahmin": ["Iyer", "Iyengar", "Saraswat", "Deshastha", "Chitpavan", "Kanyakubja", "Saryuparin", "Madhwa", "Smartha", "Vaidiki", "Nambudiri", "Gaud Saraswat", "Havyaka", "Kota", "Shivalli", "Karhade", "Daivadnya", "Bhumihar", "Tyagi", "Others"],
    "Reddy": ["Palle Reddy", "Pedakanti", "Pokanati", "Motati", "Velanati", "Bhoomanchi", "Gudati", "Others"],
    "Rajput": ["Rathore", "Chauhan", "Sisodia", "Kachwaha", "Solanki", "Parmar", "Tomar", "Parihar", "Others"],
    "Nair": ["Kiryathil", "Illathu", "Swaroopam", "Nambiar", "Menon", "Pillai", "Kurup", "Others"],
    "Maratha": ["96 Kuli", "Deshmukh", "Patil", "Kunbi", "Others"],
    "Lingayat": ["Panchamsali", "Banajiga", "Jangam", "Gowda", "Others"],
    "Kamma": ["Chowdary", "Naidu", "Others"],
    "Kapu": ["Naidu", "Balija", "Telaga", "Ontari", "Others"],
    "Vokkaliga / Gowda": ["Gangadikara", "Morasu", "Kunchitiga", "Others"],
    "Chettiar": ["Nattukottai", "Vaniya", "24 Manai", "Others"],
    "Mudaliyar / Pillai": ["Arcot", "Sengunthar", "Thuluva", "Others"],
    "Naidu": ["Kamma", "Kapu", "Balija", "Gavara", "Others"],
    "Balija": ["Gajula", "Musugu", "Others"],
    "Vanniyar / Palli": ["Padayachi", "Gounder", "Others"],
    "Thevar / Mukkulathor": ["Maravar", "Kallan", "Agamudayar", "Others"],
    "Nadar": ["Gramani", "Shanar", "Others"],
    "Vellalar": ["Saiva Pillai", "Tuluva", "Others"],
    "Arya Vysya": ["Komati", "Others"],
    "Devanga": ["Kannada Devanga", "Telugu Devanga", "Others"],
    "Agarwal / Bania": ["Bisa", "Dasa", "Oswal", "Porwal", "Maheshwari", "Others"],
    "Jat": ["Hindu Jat", "Sikh Jat", "Others"],
    "Patidar / Patel": ["Leuva", "Kadava", "Others"],
    "Yadav / Ahir": ["Gwala", "Konar", "Yadava", "Others"],
    "Kayastha": ["Saxena", "Srivastava", "Mathur", "Bhatnagar", "Nigam", "Others"],
    "Arora / Khatri": ["Arora", "Khatri", "Others"],
    "Viswakarma / Vishwakarma": ["Achari", "Kammari", "Badagi", "Others"],
    "Ezhava / Thiyya": ["Ezhava", "Thiyya", "Others"],
    "Billava": ["Others"],
    "Bunt / Shetty": ["Others"],
    "Scheduled Caste (SC)": ["Adi Dravida", "Adi Karnataka", "Mala", "Madiga", "Mahar", "Chamar", "Others"],
    "Scheduled Tribe (ST)": ["Gond", "Bhil", "Santhal", "Others"],
    "Kshatriya": ["Surya Vamsam", "Chandra Vamsam", "Others"],
    "Vaishya": ["Others"],
    "Bhumihar": ["Others"],
    "Tyagi": ["Others"],
    "Saini": ["Others"],
    "Kuruba": ["Others"],
    "Vysya": ["Others"],
    "Others": ["Others"]
};

export const GOTHRAS = [
    "Don't Know",
    "Kashyapa",
    "Bharadwaja",
    "Atri",
    "Kaushika / Vishwamitra",
    "Vashishta",
    "Agastya",
    "Gautama",
    "Jamadagni",
    "Harita",
    "Shandilya",
    "Srivatsa",
    "Koundinya",
    "Parashara",
    "Sandilya",
    "Naidhruva",
    "Upamanyu",
    "Angirasa",
    "Bhrigu",
    "Vatsa",
    "Gargya",
    "Kaundinya",
    "Mudgala",
    "Kutsa",
    "Aatreya",
    "Vishnuvriddha",
    "Sounaka",
    "Chandilya",
    "Barhaspatya",
    "Not Applicable",
    "Others"
];
